/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessPdfRouteImport } from './routes/api/process-pdf'
import { Route as ApiPublicGlobalApiMockRouteImport } from './routes/api/public/global-api-mock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessPdfRoute = ApiProcessPdfRouteImport.update({
  id: '/api/process-pdf',
  path: '/api/process-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGlobalApiMockRoute = ApiPublicGlobalApiMockRouteImport.update({
  id: '/api/public/global-api-mock',
  path: '/api/public/global-api-mock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/process-pdf': typeof ApiProcessPdfRoute
  '/api/public/global-api-mock': typeof ApiPublicGlobalApiMockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/process-pdf': typeof ApiProcessPdfRoute
  '/api/public/global-api-mock': typeof ApiPublicGlobalApiMockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/process-pdf': typeof ApiProcessPdfRoute
  '/api/public/global-api-mock': typeof ApiPublicGlobalApiMockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/process-pdf' | '/api/public/global-api-mock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/process-pdf' | '/api/public/global-api-mock'
  id: '__root__' | '/' | '/api/process-pdf' | '/api/public/global-api-mock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProcessPdfRoute: typeof ApiProcessPdfRoute
  ApiPublicGlobalApiMockRoute: typeof ApiPublicGlobalApiMockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-pdf': {
      id: '/api/process-pdf'
      path: '/api/process-pdf'
      fullPath: '/api/process-pdf'
      preLoaderRoute: typeof ApiProcessPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/global-api-mock': {
      id: '/api/public/global-api-mock'
      path: '/api/public/global-api-mock'
      fullPath: '/api/public/global-api-mock'
      preLoaderRoute: typeof ApiPublicGlobalApiMockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProcessPdfRoute: ApiProcessPdfRoute,
  ApiPublicGlobalApiMockRoute: ApiPublicGlobalApiMockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
